export { default as LoginPage } from "./LoginPage";
export { default as RegisterPage } from "./RegisterPage";
export { default as DashboardHomePage } from "./DashboardHomePage";
export { default as EmployeesPage } from "./EmployeesPage";
export { default as CandidatesPage } from "./CandidatesPage";
export { default as RecordsPage } from "./RecordsPage";
export { default as PageNotFoundPage } from "./PageNotFound";
export { default as HomePage } from "./HomePage";
export { default as ForgetPasswordPage } from "./ForgetPasswordPage";
